# default_env: &default
#   adapter: postgresql
#   encoding: unicode
#   database: c_original

# development:
#   <<: *default

# production:
#   <<: *default

default_env: &default
  adapter: postgresql
  encoding: unicode
  database: c_original

development:
  <<: *default

production:
  <<: *default
  host: dpg-cm55e021hbls73ah56h0-a
  database: c_original
  username: c_original_user
  password: X121kLP96R9hKd8TDudMEayR5WfhAruD

